version: "3.9"

services:
  frontend:
    image: sermalenk/skypro-front:lesson-34
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api


  api:
    image: .../...:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Рестарт я делал уже на деплой на сервер
    # restart: always
#    env_file:
#      - ./../.env
#      - .:/app/.env # тут по суте должен быть путь который указан в Dockerfile
    # Для работы с переменным окружением
#    environment:
#      SQL_DB_HOST: db
#      SQL_DB_PORT: 5432
#      SQL_DB_NAME: postgres
#      SQL_DB_USER: postgres
#      SQL_DB_PASSWORD: postgres
      # SECRET_KEY: ${SECRET_KEY}
#      DEBUG: ${DEBUG}
#      SOCIAL_AUTH_VK_OAUTH2_KEY: ${SOCIAL_AUTH_VK_OAUTH2_KEY}
#      SOCIAL_AUTH_VK_OAUTH2_SECRET: ${SOCIAL_AUTH_VK_OAUTH2_SECRET}
    depends_on:
      db:
        condition: service_healthy


  migrations:
    build:
      context: .
    container_name: migrations
#    environment:
#      SQL_DB_HOST: db
#      SQL_DB_PORT: 5432
#      SQL_DB_NAME: postgres
#      SQL_DB_USER: postgres
#      SQL_DB_PASSWORD: postgres
    depends_on:
      api:
        condition: service_started
      db:
        condition: service_healthy
    command: python manage.py migrate

  db:
    # Использование готового образа postgres
    image: postgres:15.2
    # Задание переменных окружения для контейнера с postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
     # Задание имени контейнера для сервиса db
    container_name: db
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      # test: ["CMD-SHELL", "pg_isready -U ${SQL_DB_USER} -d ${SQL_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 15

volumes:
  db_data:
  frontend:
